
DROP TABLE IF EXISTS `#__pubdb_Literature`;

CREATE TABLE `#__pubdb_Literature` (
  `pubdb_literatur_id` int PRIMARY KEY AUTO_INCREMENT,
  `CreatedBy` varchar(255),
  `CreatedOn` datetime,
  `ModifiedBy` varchar(255),
  `Abstract` text,
  `AccessDate` datetime,
  `BibTeXKey` text,
  `CoverPath` text,
  `Date` Date,
  `DOI` text,
  `Edition` text,
  `ISBN` text,
  `Language` text,
  `LanguageCode` text,
  `Number` text,
  `NumberOfVolume` text,
  `OnlineAddress` text,
  `OriginalCheckedDate` datetime,
  `OriginalPublicationDate` datetime,
  `PageCount` text,
  `PageRange` text,
  `Periodical_ID` int,
  `Parent_Literature_ID` int,
  `PubMedID` text,
  `ReferenceType` text,
  `SeriesTitleID` int,
  `ShortTitle` text,
  `SourceOfBibliographicInformation` text,
  `Subtitle` text,
  `Title` text,
  `TitlleInOtherLanguage` text,
  `TitleSupplement` text,
  `UniformTitle` text,
  `Volume` text,
  `Year` text,
  `eISBN` text,
  `PMCID` text,
  `ArXicID` text
);